<?php

namespace Database\Seeders;

use App\Models\Film;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class FilmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $films = [
            [
                'author' => 'Unknown',
                'model' => 'UNKNOWN',
                'year' => null,
                'duration' => null,
                'main_hero' => 'ZaglushkaNePridumal',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => null,
            ],
            [
                'author' => 'Unknown',
                'model' => 'Budget',
                'year' => null,
                'duration' => null,
                'main_hero' => 'Vazgen',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Unknown',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'BurgerMan',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'WarnerBrazzers',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'KyleTheAlien',
                'genre' => 'Action',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => null,
            ],
            [
                'author' => 'WarnerBrazzers',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'H2O',
                'genre' => 'Action',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => null,
            ],
            [
                'author' => 'WarnerBrazzers',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'ZaglushkaNePridumal2',
                'genre' => 'Action',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => null,
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Twentycentuaryfox',
                'model' => 'Budget',
                'year' => null,
                'duration' => null,
                'main_hero' => 'Aboba',
                'genre' => 'Electric',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
            ],
            [
                'author' => 'Twentycentuaryfox',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'JonnySins',
                'genre' => 'Electric',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => null,
            ],
            [
                'author' => 'LatvijasKino',
                'model' => 'Budget',
                'year' => null,
                'duration' => null,
                'main_hero' => 'IronMan',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'BEBRAPRODUCTION',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'BebraMan',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => null,
            ],
            [
                'author' => 'WarnerBrazzers',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'Roger',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => null,
                'filmImage5' => null,
                'filmImage6' => null,
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'RealityKings',
                'model' => 'Budget',
                'year' => null,
                'duration' => null,
                'main_hero' => 'Slickbag',
                'genre' => 'Drama',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Bangbros',
                'model' => 'Budget',
                'year' => null,
                'duration' => null,
                'main_hero' => 'KyleTheAlien',
                'genre' => 'Drama',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Chynachase',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'Boobs',
                'genre' => 'Action',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage7' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage8' => null,
            ],
            [
                'author' => 'JackiechanFilms',
                'model' => 'Blockbuster',
                'year' => null,
                'duration' => null,
                'main_hero' => 'Crossover',
                'genre' => 'Unknown',
                'volume' => null,
                'description' => null,
                'ndc' => null,
                'price_per_watch' => null,
                'filmImage1' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage2' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage3' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage4' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage5' => 'filmImages/82hM0Dk62kt4U1TYcZfduRYviyHXAO9uKxeGQhCf.png',
                'filmImage6' => null,
                'filmImage7' => null,
                'filmImage8' => null,
            ],
        ];

        foreach ($films as $film) {
            Film::create($film);
        }
    }
}
